//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika.Avdeev.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentReport
    {
        public int EquipmentReportID { get; set; }
        public string Name { get; set; }
        public string TechicalDescription { get; set; }
        public System.DateTime Date { get; set; }
        public int EngineerID { get; set; }
    
        public virtual User User { get; set; }
    }
}
