//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika.Avdeev.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialReport
    {
        public int FinancialReportID { get; set; }
        public int Payment { get; set; }
        public int TypeOfFinancialActivityID { get; set; }
        public System.DateTime Date { get; set; }
        public int AccountantID { get; set; }
    
        public virtual TypeOfFinancialActivity TypeOfFinancialActivity { get; set; }
        public virtual User User { get; set; }
    }
}
