//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika.Avdeev.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiringApplication
    {
        public int HiringApplicationID { get; set; }
        public string RequirementsDescription { get; set; }
        public int ProfessionID { get; set; }
        public int Count { get; set; }
        public bool IsHired_ { get; set; }
        public int EmployerID { get; set; }
    
        public virtual Profession Profession { get; set; }
        public virtual User User { get; set; }
    }
}
