//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika.Avdeev.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MineralReport
    {
        public int MneralReportID { get; set; }
        public int ExportID { get; set; }
        public int Revenue { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductionDirectorID { get; set; }
    
        public virtual Export Export { get; set; }
        public virtual User User { get; set; }
    }
}
