//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika.Avdeev.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrEntities : DbContext
    {
        private static PrEntities context;
        public static PrEntities GetContext()
        {
            if (context == null)
            {
                context = new PrEntities();
            }

            return context;
        }
        public PrEntities()
            : base("name=PrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<EquipmentReport> EquipmentReport { get; set; }
        public virtual DbSet<Export> Export { get; set; }
        public virtual DbSet<FinancialReport> FinancialReport { get; set; }
        public virtual DbSet<HiringApplication> HiringApplication { get; set; }
        public virtual DbSet<MineralReport> MineralReport { get; set; }
        public virtual DbSet<Minerals> Minerals { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<PurchaseApplication> PurchaseApplication { get; set; }
        public virtual DbSet<Reserve> Reserve { get; set; }
        public virtual DbSet<SolutionForStudy> SolutionForStudy { get; set; }
        public virtual DbSet<StudyApplication> StudyApplication { get; set; }
        public virtual DbSet<StudyCourse> StudyCourse { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfFinancialActivity> TypeOfFinancialActivity { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
